apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "maisengasse2"
  description: "maisengasse2"
  tags:
    - sx
    - template
  links:
    - url: https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-qa&var-workload=maisengasse2&var-service=maisengasse2
      title: Grafana SRE Metrics
      icon: web
    - url: http://maisengasse2-suxess-it-qa.apps.cluster1.mcp.pitagora.at
      title: maisengasse2 Service Route
      icon: web
  annotations:
    github.com/project-slug: phac008/maisengasse2-gitops
    backstage.io/kubernetes-id: maisengasse2
    kubecost.com/deployment-name: maisengasse2
    argocd/app-name: maisengasse2-qa
    backstage.io/kubernetes-namespace: suxess-it-qa
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: "https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-qa&var-workload=maisengasse2&var-service=maisengasse2"
spec:
  type: service
  lifecycle: experimental
  owner: group:default/jokl
  system: system:maisengasse2
  dependsOn:
    - resource:argocd
