apiVersion: apps/v1
kind: Deployment
metadata:
  name: maisengasse2
  namespace: suxess-it-qa
  labels:
    app: maisengasse2
    backstage.io/kubernetes-id: maisengasse2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maisengasse2
  template:
    metadata:
      labels:
        app: maisengasse2
        backstage.io/kubernetes-id: maisengasse2
    spec:
      containers:
#      - image: quay.io/rbaumgar/monitor-demo-app-jvm
      - image: quay.io/rbaumgar/monitor-demo-app-jvm
        imagePullPolicy: Always
        name: maisengasse2