apiVersion: v1
kind: Service
metadata:
  name: maisengasse2
  namespace: suxess-it-qa
  labels:
    app: maisengasse2
    backstage.io/kubernetes-id: maisengasse2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: maisengasse2
  type: ClusterIP